name: M2 PHPStan
on: [push, pull_request, workflow_dispatch]

jobs:
  phpstan:
    name: M2 PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extdn/github-actions-m2/magento-phpstan@master
        with:
          composer_name: advocodo/module-cart-quantity-multiple
